python xgboost_pi.py -t 1
python xgboost_pi.py -t 2
python xgboost_pi.py -t 3
python xgboost_pi.py -t 4
python xgboost_pi.py -t 5
python xgboost_pi.py -t 6
python xgboost_pi.py -t 7
python xgboost_pi.py -t 8
python xgboost_pi.py -t 9
python xgboost_pi.py -t 10
python xgboost_pi.py -t 11
python xgboost_pi.py -t 12
python xgboost_pi.py -t 13
python xgboost_pi.py -t 14
python xgboost_pi.py -t 15
python xgboost_pi.py -t 16
python xgboost_pi.py -t 17
python xgboost_pi.py -t 18
python xgboost_pi.py -t 19
python xgboost_pi.py -t 20
python xgboost_pi.py -t 21
python xgboost_pi.py -t 22
python xgboost_pi.py -t 23
python xgboost_pi.py -t 24
python xgboost_pi.py -t 25
python xgboost_pi.py -t 26
python xgboost_pi.py -t 27
python xgboost_pi.py -t 28
python xgboost_pi.py -t 29
python xgboost_pi.py -t 30
python xgboost_pi.py -t 31
python xgboost_pi.py -t 32